name: slopify

services:
  traefik:
    image: traefik:v3.3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "dev.orbstack.domains=slopify.local"

  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slopify
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:8.1.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.14.0
    environment:
      MEILI_MASTER_KEY: masterkey
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/data.ms
    healthcheck:
      test: ["CMD", "curl", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  account-migrations:
    image: migrate/migrate:4
    volumes:
      - ./account/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-path", "/migrations/", "-database", "postgres://postgres:postgres@postgres:5432/slopify?sslmode=disable&x-migrations-table=account-schema", "up"]

  product-migrations:
    image: migrate/migrate:4
    volumes:
      - ./product/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-path", "/migrations/", "-database", "postgres://postgres:postgres@postgres:5432/slopify?sslmode=disable&x-migrations-table=product-schema", "up"]    

  account-service:
    build:
      context: .
      dockerfile: account/Dockerfile
    environment:
      ENV_NAME: account
      ENV_RESTSERVERADDRESS: :3003
      ENV_GRPCSERVERADDRESS: :4000
      ENV_AUTHSERVICEADDRESS: auth-service:6000
      ENV_POSTGRES_USER: postgres
      ENV_POSTGRES_PASSWORD: postgres
      ENV_POSTGRES_HOST: postgres
      ENV_POSTGRES_PORT: 5432
      ENV_POSTGRES_DBNAME: slopify
      ENV_POSTGRES_SSL: "false"
      ENV_OTELCOLLECTORURL: "otel-collector:4317"
    ports:
      - "3003:3003"
      - "4000:4000"
    depends_on:
      account-migrations:
        condition: service_completed_successfully
      product-migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      otel-collector:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.account.rule=PathPrefix(`/v1/api/account`)"
      - "traefik.http.routers.account.entrypoints=web"
      - "traefik.http.services.account.loadbalancer.server.port=3003"
      - "traefik.http.middlewares.account-stripprefix.stripprefix.prefixes=/v1/api/account"
      - "traefik.http.routers.account.middlewares=account-stripprefix"
      - "logging=promtail"
    restart: "unless-stopped"

  auth-service:
    build:
      context: .
      dockerfile: auth/Dockerfile
    environment:
      ENV_NAME: auth
      ENV_RESTSERVERADDRESS: :3001
      ENV_GRPCSERVERADDRESS: :6000
      ENV_ACCOUNTSERVICEADDRESS: account-service:4000
      ENV_VALKEY_USER: default
      ENV_VALKEY_PASSWORD: default
      ENV_VALKEY_HOST: valkey
      ENV_VALKEY_PORT: 6379
      ENV_VALKEY_DBNUMBER: 1
      ENV_SECRETS_ACCESSTOKEN: justforshow 
      ENV_SECRETS_REFRESHTOKEN: nottherealone
      ENV_OTELCOLLECTORURL: "otel-collector:4317"
    ports:
      - "3001:3001"
      - "6000:6000"
    depends_on:
      valkey:
        condition: service_healthy
      account-service:
        condition: service_started
      otel-collector:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/v1/api/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/v1/api/auth"
      - "traefik.http.routers.auth.middlewares=auth-stripprefix"
      - "logging=promtail"
    restart: "unless-stopped"

  product-service:
    build:
      context: .
      dockerfile: product/Dockerfile
    environment:
      ENV_NAME: product
      ENV_RESTSERVERADDRESS: :3002
      ENV_AUTHSERVICEADDRESS: auth-service:6000
      ENV_POSTGRES_USER: postgres
      ENV_POSTGRES_PASSWORD: postgres
      ENV_POSTGRES_HOST: postgres
      ENV_POSTGRES_PORT: 5432
      ENV_POSTGRES_DBNAME: slopify
      ENV_POSTGRES_SSL: "false"
      ENV_MEILISEARCH_URL: http://meilisearch:7700
      ENV_MEILISEARCH_KEY: masterkey
      ENV_OTELCOLLECTORURL: "otel-collector:4317"
    ports:
      - "3002:3002"
    depends_on:
      account-migrations:
        condition: service_completed_successfully
      product-migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
      auth-service:
        condition: service_started
      otel-collector:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.product.rule=PathPrefix(`/v1/api/product`)"
      - "traefik.http.routers.product.entrypoints=web"
      - "traefik.http.services.product.loadbalancer.server.port=3002"
      - "traefik.http.middlewares.product-stripprefix.stripprefix.prefixes=/v1/api/product"
      - "traefik.http.routers.product.middlewares=product-stripprefix"
      - "logging=promtail"
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318" 
    volumes:
      - ./deploy/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    depends_on:
      - loki
      - tempo
      - mimir
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/loki-config.yaml"]
    volumes:
      - ./deploy/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    restart: unless-stopped
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    command: ["-config.file=/etc/promtail/promtail-config.yaml"]
    volumes:
      - ./deploy/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - promtail_positions:/tmp 
    depends_on:
      - loki 
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./deploy/tempo-config.yaml:/etc/tempo.yaml:ro
      - tempo_data:/var/tempo
    depends_on:
      - loki 
    restart: unless-stopped
    ports:
      - "3200:3200"

  mimir:
    image: grafana/mimir:latest
    command: ["-target=all", "-config.file=/etc/mimir.yaml"] 
    volumes:
      - ./deploy/mimir-config.yaml:/etc/mimir.yaml:ro
      - mimir_data:/data/mimir 
    restart: unless-stopped
    ports:
      - "9009:9009"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana 
      - ./deploy/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
      - tempo
      - mimir
    ports:
      - "3000:3000"
    restart: unless-stopped


volumes:
  postgres_data:
  valkey_data:
  meilisearch_data:
  loki_data:
  tempo_data:
  mimir_data:
  grafana_data:
  promtail_positions:
