name: "account"
restserveraddress: ":3000"
grpcserveraddress: ":4000"
authserviceaddress: ":6000"
postgres:
    user: "postgres" 
    password: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "slopify"
    ssl: false
