name: "auth"
version: "0.0.1"
restserveraddress: ":3001"
grpcserveraddress: ":6000"
accountserviceaddress: ":4000"
valkey:
    user: "default" 
    password: "default"
    host: "localhost"
    port: "6379"
    dbnumber: "1"
secrets:
  accesstoken: "onlyfortest"
  refreshtoken: "onlyfortest"
otelcollectorurl: "0.0.0.0:4317"
