receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/tempo:
    endpoint: "http://tempo:4318" 
    tls:
      insecure: true 

  prometheusremotewrite/mimir:
    endpoint: "http://mimir:9009/api/v1/push" 
    tls:
      insecure: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push" 
    tls:
      insecure: true

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25

service:
  extensions: [] 
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite/mimir]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [loki]

  telemetry: 
    logs:
      level: info
