positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
    
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            port: port
            time: time
            message: message
            error: error
      
      - timestamp:
          source: time
          format: RFC3339
      
      - labels:
          level:
          service:
      
      - match:
          selector: '{level="error"}'
          stages:
            - metrics:
                error_count:
                  type: Counter
                  description: "Count of error logs"
                  source: level
                  config:
                    action: inc
      
      - regex:
          expression: ".*server (started|stared)$"
          source: message
          stages:
            - regex:
                source: message
                expression: ".*(rest|grpc) server.*"
                capture:
                  - server_type
            - labels:
                server_type:
