name: "product"
version: "0.0.1"
restserveraddress: ":3002"
authserviceaddress: ":6000"
postgres:
    user: "postgres" 
    password: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "slopify"
    ssl: false
meilisearch:
    url: "http://localhost:7700"
    key: "masterkey"
otelcollectorurl: "0.0.0.0:4317"
