// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type Product struct {
	ID              int32   `json:"id"`
	Title           string  `json:"title"`
	Description     string  `json:"description"`
	Category        string  `json:"category"`
	Price           float32 `json:"price"`
	Discount        float32 `json:"discount"`
	QuantityInStock int32   `json:"quantity_in_stock"`
}
